# Generated by Django 3.2.21 on 2023-11-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevoregistro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
