# Generated by Django 3.2.21 on 2023-11-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iniciar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('aprobada', models.BooleanField(default=False)),
                ('referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('detalles', models.CharField(blank=True, max_length=20, null=True)),
                ('tasa_interes', models.FloatField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='iniciar.nuevoregistro')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='iniciar.nuevoregistro')),
            ],
        ),
    ]
